runtime: nodejs14
entrypoint: node -r dotenv/config ./dist/apps/backend/main.js
handlers:
  - url: /static
    static_dir: dist/apps/frontend2020/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  BUCKET: "lessoneditor"
  GITHUB_LESSON_REPO: "oppgaver"
  GITHUB_LESSON_REPO_OWNER: "kodeklubben"
  THUMB_SERVICE_URL: "https://europe-west1-lessoneditor.cloudfunctions.net/thumbnailer"
