@REM set GITHUB_CLIENT_ID=0a838d7f4cd79f2005b6
@REM set GITHUB_CLIENT_SECRET=6e1f0cdb26e59eb7ccfc9cc0bcd00a3524ab65ee
@REM set GITHUB_CALLBACK_URL=http://localhost:4200/api/auth/callback
@REM set THUMB_SERVICE_URL=http://localhost:3012/
@REM set GITHUB_LESSON_REPO_OWNER=kodeklubben
@REM set GITHUB_LESSON_REPO=oppgaver
@REM set TYPEORM_CONNECTION=postgres
@REM set TYPEORM_HOST=localhost
@REM set TYPEORM_USERNAME=orm-user
@REM set TYPEORM_PASSWORD=testing
@REM set TYPEORM_DATABASE=lesson-editor
@REM set TYPEORM_PORT=5432
@REM set TYPEORM_SYNCHRONIZE=false
@REM set TYPEORM_ENTITIES= dist/**/*.entity.js
