import { DEFAULT_TEXT } from "../../../settingsFiles/languages/editor_NO";

// SHORTCUTKEY options: "ctrl", "shift", "alt", "option", "command"
const SHORTCUTKEY = "ctrl";
const SHORTCUTKEY2 = "shift";

// SHORTCUTKEYS config
const KEY_COMBINATIONS_MICROBIT = {
  basic: [SHORTCUTKEY, "+", "1"].join(""),
  input: [SHORTCUTKEY, "+", "2"].join(""),
  music: [SHORTCUTKEY, "+", "3"].join(""),
  led: [SHORTCUTKEY, "+", "4"].join(""),
  radio: [SHORTCUTKEY, "+", "5"].join(""),
  loops: [SHORTCUTKEY, "+", "6"].join(""),
  logic: [SHORTCUTKEY, "+", "7"].join(""),
  variables: [SHORTCUTKEY, "+", "8"].join(""),
  math: [SHORTCUTKEY, "+", "9"].join(""),
  functions: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "1"].join(""),
  arrays: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "2"].join(""),
  text: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "3"].join(""),
  game: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "4"].join(""),
  images: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "5"].join(""),
  pins: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "6"].join(""),
  serial: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "7"].join(""),
  control: [SHORTCUTKEY, "+", SHORTCUTKEY2, "+", "8"].join(""),
};

const KEY_COMBINATIONS_SCRATCH = {
  motion: [SHORTCUTKEY, "+", "1"].join(""),
  looks: [SHORTCUTKEY, "+", "2"].join(""),
  sound: [SHORTCUTKEY, "+", "3"].join(""),
  pen: [SHORTCUTKEY, "+", "4"].join(""),
  data: [SHORTCUTKEY, "+", "5"].join(""),
  events: [SHORTCUTKEY, "+", "6"].join(""),
  control: [SHORTCUTKEY, "+", "7"].join(""),
  sensing: [SHORTCUTKEY, "+", "8"].join(""),
  operators: [SHORTCUTKEY, "+", "9"].join(""),
  moreblocks: [SHORTCUTKEY, "+", "0"].join(""),
};

const microbitbuttons = {
  basic: {
    slug: "basic",
    output: "`" + DEFAULT_TEXT + "`{.microbitbasic}",
    title: "Basis",
    cursorIntON: 1,
    cursorIntOFF: 17,
    shortcut: KEY_COMBINATIONS_MICROBIT.basic,
    color: "#1e90ff",
  },
  input: {
    slug: "input",
    output: "`" + DEFAULT_TEXT + "`{.microbitinput}",
    title: "Inndata",
    cursorIntON: 1,
    cursorIntOFF: 17,
    shortcut: KEY_COMBINATIONS_MICROBIT.input,
    color: "#d400d4",
  },
  music: {
    slug: "music",
    output: "`" + DEFAULT_TEXT + "`{.microbitmusic}",
    title: "Musikk",
    cursorIntON: 1,
    cursorIntOFF: 17,
    shortcut: KEY_COMBINATIONS_MICROBIT.music,
    color: "#e63022",
  },
  led: {
    slug: "led",
    output: "`" + DEFAULT_TEXT + "`{.microbitled}",
    title: "Skjerm",
    cursorIntON: 1,
    cursorIntOFF: 15,
    shortcut: KEY_COMBINATIONS_MICROBIT.led,
    color: "#5c2d91",
  },
  radio: {
    slug: "radio",
    output: "`" + DEFAULT_TEXT + "`{.microbitradio}",
    title: "Radio",
    cursorIntON: 1,
    cursorIntOFF: 17,
    shortcut: KEY_COMBINATIONS_MICROBIT.radio,
    color: "#e3008c",
  },
  loops: {
    slug: "loops",
    output: "`" + DEFAULT_TEXT + "`{.microbitloops}",
    title: "Løkker",
    cursorIntON: 1,
    cursorIntOFF: 17,
    shortcut: KEY_COMBINATIONS_MICROBIT.loops,
    color: "#0a0",
  },
  logic: {
    slug: "logic",
    output: "`" + DEFAULT_TEXT + "`{.microbitlogic}",
    title: "Logikk",
    cursorIntON: 1,
    cursorIntOFF: 17,
    shortcut: KEY_COMBINATIONS_MICROBIT.logic,
    color: "#00a4a6",
  },
  variables: {
    slug: "variables",
    output: "`" + DEFAULT_TEXT + "`{.microbitvariables}",
    title: "Variabler",
    cursorIntON: 1,
    cursorIntOFF: 21,
    shortcut: KEY_COMBINATIONS_MICROBIT.variables,
    color: "#dc143c",
  },
  math: {
    slug: "math",
    output: "`" + DEFAULT_TEXT + "`{.microbitmath}",
    title: "Matematikk",
    cursorIntON: 1,
    cursorIntOFF: 16,
    shortcut: KEY_COMBINATIONS_MICROBIT.math,
    color: "#9400d3",
  },
  functions: {
    slug: "functions",
    output: "`" + DEFAULT_TEXT + "`{.microbitfunctions}",
    title: "Funksjoner",
    cursorIntON: 1,
    cursorIntOFF: 21,
    shortcut: KEY_COMBINATIONS_MICROBIT.functions,
    color: "#3455db",
  },
  arrays: {
    slug: "arrays",
    output: "`" + DEFAULT_TEXT + "`{.microbitarrays}",
    title: "Tabeller",
    cursorIntON: 1,
    cursorIntOFF: 18,
    shortcut: KEY_COMBINATIONS_MICROBIT.arrays,
    color: "#e65722",
  },
  text: {
    slug: "text",
    output: "`" + DEFAULT_TEXT + "`{.microbittext}",
    title: "Tekst",
    cursorIntON: 1,
    cursorIntOFF: 16,
    shortcut: KEY_COMBINATIONS_MICROBIT.text,
    color: "#b8860b",
  },
  game: {
    slug: "game",
    output: "`" + DEFAULT_TEXT + "`{.microbitgame}",
    title: "Spill",
    cursorIntON: 1,
    cursorIntOFF: 16,
    shortcut: KEY_COMBINATIONS_MICROBIT.game,
    color: "#007a4b",
  },
  images: {
    slug: "images",
    output: "`" + DEFAULT_TEXT + "`{.microbitimages}",
    title: "Bilder",
    cursorIntON: 1,
    cursorIntOFF: 18,
    shortcut: KEY_COMBINATIONS_MICROBIT.images,
    color: "#7600a8",
  },
  pins: {
    slug: "pins",
    output: "`" + DEFAULT_TEXT + "`{.microbitpins}",
    title: "Tilkobling",
    cursorIntON: 1,
    cursorIntOFF: 16,
    shortcut: KEY_COMBINATIONS_MICROBIT.pins,
    color: "#b22222",
  },
  serial: {
    slug: "serial",
    output: "`" + DEFAULT_TEXT + "`{.microbitserial}",
    title: "Serieport",
    cursorIntON: 1,
    cursorIntOFF: 18,
    shortcut: KEY_COMBINATIONS_MICROBIT.serial,
    color: "#002050",
  },
  control: {
    slug: "control",
    output: "`" + DEFAULT_TEXT + "`{.microbitcontrol}",
    title: "Styring",
    cursorIntON: 1,
    cursorIntOFF: 19,
    shortcut: KEY_COMBINATIONS_MICROBIT.control,
    color: "#333",
  },
};

const scratchbuttons = {
  motion: {
    slug: "motion",
    output: "`" + DEFAULT_TEXT + "`{.blockmotion}",
    title: "Bevegelse",
    cursorIntON: 1,
    cursorIntOFF: 15,
    shortcut: KEY_COMBINATIONS_SCRATCH.motion,
    color: "#4c97ff",
  },
  looks: {
    slug: "looks",
    output: "`" + DEFAULT_TEXT + "`{.blocklooks}",
    title: "Utseende",
    cursorIntON: 1,
    cursorIntOFF: 14,
    shortcut: KEY_COMBINATIONS_SCRATCH.looks,
    color: "#96f",
  },
  sound: {
    slug: "sound",
    output: "`" + DEFAULT_TEXT + "`{.blocksound}",
    title: "Lyd",
    cursorIntON: 1,
    cursorIntOFF: 14,
    shortcut: KEY_COMBINATIONS_SCRATCH.sound,
    color: "#cf63cf",
  },
  pen: {
    slug: "pen",
    output: "`" + DEFAULT_TEXT + "`{.blockpen}",
    title: "Penn",
    cursorIntON: 1,
    cursorIntOFF: 12,
    shortcut: KEY_COMBINATIONS_SCRATCH.pen,
    color: "#0fbd8c",
  },
  data: {
    slug: "data",
    output: "`" + DEFAULT_TEXT + "`{.blockdata}",
    title: "Variabler",
    cursorIntON: 1,
    cursorIntOFF: 13,
    shortcut: KEY_COMBINATIONS_SCRATCH.data,
    color: "#ff8c1a",
  },
  events: {
    slug: "events",
    output: "`" + DEFAULT_TEXT + "`{.blockevents}",
    title: "Hendelser",
    cursorIntON: 1,
    cursorIntOFF: 15,
    shortcut: KEY_COMBINATIONS_SCRATCH.events,
    color: "#ffbf00",
  },
  control: {
    slug: "control",
    output: "`" + DEFAULT_TEXT + "`{.blockcontrol}",
    title: "Styring",
    cursorIntON: 1,
    cursorIntOFF: 16,
    shortcut: KEY_COMBINATIONS_SCRATCH.control,
    color: "#ffab19",
  },
  sensing: {
    slug: "sensing",
    output: "`" + DEFAULT_TEXT + "`{.blocksensing}",
    title: "Sansing",
    cursorIntON: 1,
    cursorIntOFF: 16,
    shortcut: KEY_COMBINATIONS_SCRATCH.sensing,
    color: "#5cb1d6",
  },
  operators: {
    slug: "operators",
    output: "`" + DEFAULT_TEXT + "`{.blockoperators}",
    title: "Operatorer",
    cursorIntON: 1,
    cursorIntOFF: 18,
    shortcut: KEY_COMBINATIONS_SCRATCH.operators,
    color: "#59c059",
  },
  moreblocks: {
    slug: "moreblocks",
    output: "`" + DEFAULT_TEXT + "`{.blockmoreblocks}",
    title: "Mine klosser",
    cursorIntON: 1,
    cursorIntOFF: 19,
    shortcut: KEY_COMBINATIONS_SCRATCH.moreblocks,
    color: "#ff6680",
  },
};

export { microbitbuttons, scratchbuttons, KEY_COMBINATIONS_MICROBIT, KEY_COMBINATIONS_SCRATCH };
