export default {
  bold: false,
  italic: false,
  heading: false,
  strikethrough: false,
  undo: false,
  redo: false,
  new: false,
  load: false,
  save: false,
  image: false,
  listUl: false,
  listOl: false,
  listCheck: false,
  sec_activity: false,
  sec_intro: false,
  sec_check: false,
  sec_tip: false,
  sec_protip: false,
  sec_challenge: false,
  sec_flag: false,
  sec_try: false,
  inline: false,
  codeblock: false,
};
