export default {
  bold: true,
  italic: true,
  heading: true,
  strikethrough: true,
  undo: true,
  redo: true,
  new: true,
  load: true,
  save: true,
  image: true,
  listUl: true,
  listOl: true,
  listCheck: true,
  sec_activity: true,
  sec_intro: true,
  sec_check: true,
  sec_tip: true,
  sec_protip: true,
  sec_challenge: true,
  sec_flag: true,
  sec_try: true,
  inline: true,
  codeblock: true,
};
