name: Build, push, and deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test and Build Apps
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run test-all
      - run: npm run test-backend
      - run: npm run build-all
      - run: npm run build-backend
      - name: Caching Dist Folder
        uses: actions/cache@v2
        with:
          path: ./dist
          key: cache-dist-${{ github.sha }}

  deploy_db:
    name: Deploy to Cloud SQL Postgres
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    timeout-minutes: 5
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm ci
      - name: install cloud sql auth proxy
        run: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: erik-lessoneditor
          APPLICATION_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT }}
        with:
          args: info
      - name: fetch access token
        run: echo ${{ secrets.SERVICE_ACCOUNT }} | base64 --decode > credentials.json
      - run: gcloud auth activate-service-account github-actions@erik-lessoneditor.iam.gserviceaccount.com --key-file=credentials.json
      - run: gcloud auth print-access-token
      - run: ACCESS_TOKEN=$(gcloud auth print-access-token); echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

      - name: run migrations
        run: (./cloud_sql_proxy -instances=erik-lessoneditor:europe-west1:lesson-editor=tcp:5432 -credential_file=credentials.json & sleep 2) && typeorm -d dist/apps/backend/db/data-sources.js -- migration:run
        env:
          TYPEORM_CONNECTION: postgres
          TYPEORM_HOST: localhost
          TYPEORM_USERNAME: github-actions@erik-lessoneditor.iam
          TYPEORM_PASSWORD: ${{ env.ACCESS_TOKEN }}
          TYPEORM_DATABASE: erik-lessoneditor
          TYPEORM_PORT: 5432
          TYPEORM_SYNCHRONIZE: false
          TYPEORM_MIGRATIONS: db/migration/**/*.ts
          TYPEORM_MIGRATIONS_DIR: db/migration
          TYPEORM_ENTITIES: apps/backend/src/user/user.entity.ts,apps/backend/src/lesson/lesson.entity.ts,apps/backend/src/session/session.entity.ts

  deploy:
    timeout-minutes: 9
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Restoring Dist Folder
        uses: actions/cache@v2
        with:
          path: ./dist
          key: cache-dist-${{ github.sha }}
      - id: "auth"
        uses: "google-github-actions/auth@v0.4.1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"
      - name: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: "erik-lessoneditor"
