name: Build, push, and deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   name: Run Test and Build Apps
  #   timeout-minutes: 3
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"

  #     - run: npm ci

  #     - name: Cache Node Modules
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: npm-deps-${{ hashFiles('package-lock.json') }}

  #     - run: npm run test-all

  #     - run: npm run build-all

  #     - name: Cache Dist Folder
  #       uses: actions/cache@v3
  #       with:
  #         path: ./dist
  #         key: cache-dist-${{ github.sha }}

  deploy_db:
    name: Deploy to Cloud SQL Postgres
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Since we're using the same node version, cached node modules will be reused
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - run: npm run build-backend
      # - run: npm install -g ts-node

      - name: Install Cloud SQL Auth Proxy
        run: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy

      - name: Start Cloud SQL Proxy
        run: ./cloud_sql_proxy -instances=erik-lessoneditor:europe-north1:lesson-editor=tcp:5432 -credential_file=credentials.json &
        env:
          CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Run Migrations
        run: (./cloud_sql_proxy -instances=erik-lessoneditor:europe-north1:lesson-editor=tcp:5432 -credential_file=credentials.json & sleep 2) && npm run typeorm migration:run
        env:
          TYPEORM_CONNECTION: postgres
          TYPEORM_HOST: localhost
          TYPEORM_USERNAME: postgres
          TYPEORM_PASSWORD: pai_kjelke_bever
          TYPEORM_DATABASE: lesson-editor
          TYPEORM_PORT: 5432
          TYPEORM_SYNCHRONIZE: false
          TYPEORM_MIGRATIONS: db/migration/**/*.ts
          TYPEORM_MIGRATIONS_DIR: db/migration
          TYPEORM_ENTITIES: apps/backend/src/user/user.entity.ts,apps/backend/src/lesson/lesson.entity.ts,apps/backend/src/session/session.entity.ts

  # deploy:
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   timeout-minutes: 9
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   name: Deploy to Google App Engine
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #     - name: Restoring Dist Folder
  #       uses: actions/cache@v3
  #       with:
  #         path: ./dist
  #         key: cache-dist-${{ github.sha }}

  #     - id: "auth"
  #       name: "Authenticate to Google Cloud"
  #       uses: "google-github-actions/auth@v1"
  #       with:
  #         credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

  #     - id: "deploy"
  #       uses: "google-github-actions/deploy-appengine@v1"
  #       with:
  #         project_id: "erik-lessoneditor"
